### ISSUE TITLE
No preview appear for material:MaterialTextField in Xaml Previewer

### ISSUE THREAD

**Issue by MuhammadJazabDMT** [BaseflowIT/XF-Material-Library#183]
Am using material:MaterialTextField and it doesn't appear on Xaml previewer. i have to rebuild application every time i made some changes. haven't check other controls yet.

**Comment by Miiite** [comment]
You're right it doesn't, but I doubt this is something that can be fixed by this repository maintainers. It works fine with Xamarin XAML Hot Reload. You might want to enable the feature in Visual Studio Preferences, to make it easier for you to debug this control live.
You need the latest version of visual studio (stable branch) to do so
